export const SEND_PROMPT_REQUEST = 'SEND_PROMPT_REQUEST';
export const SEND_PROMPT_SUCCESS = 'SEND_PROMPT_SUCCESS';
export const SEND_PROMPT_FAIL = 'SEND_PROMPT_FAIL';

export const USER_PROMPTS_REQUEST = 'USER_PROMPT_REQUEST';
export const USER_PROMPTS_SUCCESS = 'USER_PROMPT_SUCCESS';
export const USER_PROMPTS_FAIL = 'USER_PROMPT_FAIL';